HelmChartPath: ''
RepoName: helloworldbgl/uptime-kuma1
RunCommand: |
  echo "start run command"
SourceCodePath: .
CommandTimeout: 3600
SecurityGroupPorts:
- '3001'
RuntimeType: LinuxShell
ServicePorts:
- '3001'
ServiceType: private
ArtifactSourceType: SourceCode
ServiceBuildRegion: ap-southeast-1
ImageId: '"{{resolve:oos:aliyun/services/ecs/images/linux/aliyun-latest/alibaba_cloud_linux_3_2104_lts_x64}}"'
RegionId: cn-hangzhou
CustomParameters: ''
Owner: helloworldbgl
Branch: master
Platform: github
